# 워크플로우 이름을 지정
name: Deploy to LightSail

# 트리거 설정: github action이 언제 발동될지를 결정
on:
  push:
    branches:
      - main      # main branch를 push하면 actions를 실행.

env:
  # 환경 변수 지정
  IMAGE_NAME: donggyunham/auth

# 실제로 실행할 actions들을 여기다 정의
jobs:
  # 작업 이름 부여
  build-and-deploy:
    runs-on: ubuntu-latest

    # 권한 설정: 어떤 일을 할 수 있는지 정의
    permissions:
      contents: read    # repository의 코드를 읽을 수 있는 권한을 부여
      packages: write   # github container registry(GHCR)의 docker image를 upload(save)할 수 있는 권한 부여

    # 아래에 정의되는 step(작업단위) 순서대로 작업을 처리함
    steps:
      - name: Code Check-out
        uses: actions/checkout@v4

      - name: Java 17 Setup
        uses: actions/setup-java@v4   # java 설치 action(https://github.com/marketplace?query=setup&type=actions)
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Build
        # ./gradlew 빌드 실행 명령의 실행 권한 부여.
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test --no-daemon
